---
title: "COVID-19 Data by State"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r import-packages}
library(tidyverse)
```


```{r import-data}
rawdata <- read.csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")

# Temperarily make it comment while developing
# poprawdata <- read.csv("https://www2.census.gov/programs-surveys/popest/datasets/2010-2019/state/detail/SCPRC-EST2019-18+POP-RES.csv")

poprawdata <- read.csv("./tmp/SCPRC-EST2019-18+POP-RES.csv")
```

### COVID-19 Historical U.S. State-Level Data from the New York Times
```{r}
tail(rawdata, 10)
```
<U.S. tracking page by the New York Times> [link](https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html)   





### 2019 State Population Estimates
```{r}
tail(poprawdata, 10)
```
<State Population Totals: 2010-2019> [link](https://www.census.gov/data/datasets/time-series/demo/popest/2010s-state-total.html)

```{r}
# Get data on the latest day
thelatestdate <- max(rawdata[[1]])
thepreviousdate<- as.character(as.Date(thelatestdate) - 1)

thelatest <-
  rawdata %>%
  filter(date %in% c(thelatestdate)) %>%
  select(state, fips) %>%
  mutate(
    !!thelatestdate := 
      rawdata$cases[which(rawdata$date == thelatestdate)] - 
      rawdata$cases[which(rawdata$date == thepreviousdate)]
  )
  
thelatest <-
  thelatest %>%
  mutate(
    pop = poprawdata$POPESTIMATE2019[match(state, poprawdata$NAME)],
    percap = round(thelatest[[thelatestdate]] / pop * 100000, digit = 2)
  )
```


```{r}
# Plot the distribution of cases on the latest date
  ggplot(
    data = thelatest, 
    mapping = aes(x = thelatest[[3]])
  ) +
  geom_histogram() +
  labs (
    title = paste("New Cases on ", thelatestdate), 
    x = ""
  )

```

```{r}
# Plot the distribution of cases per 100K on the latest date 
  ggplot(
    data = thelatest, 
    mapping = aes(x = percap)
  ) +
  geom_histogram() +
  labs (
    title = paste("New Cases per 100K on ", thelatestdate),
    x = ""
  )


```

